<?php

/**
 * @file
 * Module file for Asynk asynchronous actions.
 */

/**
 * Implements Asynchronous actions.
 */
function asynk() {

  $params = array_merge(array('asynk_request'), func_get_args());
  call_user_func_array('register_shutdown_function', $params);
}

/**
 * Asynk reques.
 */
function asynk_request() {

  $options = array(
    'method' => 'POST',
    'data' => drupal_http_build_query(func_get_args()),
    'timeout' => 2,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  );
  drupal_http_request(url('asynk', array('absolute' => TRUE)), $options);
}

/**
 * Implements hook_theme().
 *
 * Use our custom designed template for registration form.
 */
function asynk_menu() {

  $items = array();

  // Linkage request reject.
  $items['asynk'] = array(
    'access callback' => TRUE,
    'page callback' => 'asynk_request_handler',
  );

  return $items;
}

/**
 * Request handler.
 */
function asynk_request_handler() {

  $data = $_POST;
  if (!empty($_POST['0'])) {
    unset($data['0']);
    call_user_func_array($_POST['0'], $data);
    exit();
  }
}

function asynk_test($title, $title2) {

  $node = node_load(1);
  $node->title = $title2;
  node_save($node);
}