<?php

/**
 * @file
 * Module file for registration related actions.
 */

/**
 * Implements Asynchronous actions.
 */
function asynk_init() {

  if (isset($_GET['asynk'])) {
    asynk('test', $_GET['asynk']);
  }
}

/**
 * Implements Asynchronous actions.
 */
function asynk($action, $data) {

  $params = array('asynk_request', $data);
  //register_shutdown_function('asynk_request');
  call_user_func_array('register_shutdown_function', $params);
}

/**
 * Asynk reques.
 */
function asynk_request() {

  $args = func_get_args();
  $data['title'] = $args[0];
  $options = array(
    'method' => 'POST',
    'data' => drupal_http_build_query($data),
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  );
  drupal_http_request(url('asynk', array('absolute' => TRUE)), $options);
}

/**
 * Implements hook_theme().
 *
 * Use our custom designed template for registration form.
 */
function asynk_menu() {

  $items = array();

  // Linkage request reject.
  $items['asynk'] = array(
    'access callback' => TRUE,
    'page callback' => 'asynk_request_handler',
  );

  return $items;
}

/**
 * Request handler.
 */
function asynk_request_handler() {

  $title = $_POST['title'];
  $node = node_load(1);
  $node->title = $title;
  node_save($node);
}
